<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="2" passed="1" failed="0" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-18T00:34:54 EET" name="Default suite" finished-at="2023-04-18T00:35:06 EET" duration-ms="11891">
    <groups>
    </groups>
    <test started-at="2023-04-18T00:34:54 EET" name="Default test" finished-at="2023-04-18T00:35:06 EET" duration-ms="11891">
      <class name="TestCases.LoginPageTest">
        <test-method is-config="true" signature="SetUpDriver()[pri:0, instance:TestCases.LoginPageTest@e1e2e5e]" started-at="2023-04-18T00:34:54 EET" name="SetUpDriver" finished-at="2023-04-18T00:35:01 EET" duration-ms="6852" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SetUpDriver -->
        <test-method signature="validLogin()[pri:0, instance:TestCases.LoginPageTest@e1e2e5e]" started-at="2023-04-18T00:35:01 EET" name="validLogin" finished-at="2023-04-18T00:35:05 EET" duration-ms="4478" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validLogin -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:TestCases.LoginPageTest@e1e2e5e]" started-at="2023-04-18T00:35:05 EET" name="tearDown" finished-at="2023-04-18T00:35:06 EET" duration-ms="164" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=validLogin status=SUCCESS method=LoginPageTest.validLogin()[pri:0, instance:TestCases.LoginPageTest@e1e2e5e] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="runReport()[pri:0, instance:TestCases.LoginPageTest@e1e2e5e]" started-at="2023-04-18T00:35:06 EET" name="runReport" finished-at="2023-04-18T00:35:06 EET" duration-ms="4" status="FAIL">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Cannot run program "allure.bat": CreateProcess error=2, The system cannot find the file specified]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Cannot run program "allure.bat": CreateProcess error=2, The system cannot find the file specified
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
at java.base/java.lang.Runtime.exec(Runtime.java:594)
at java.base/java.lang.Runtime.exec(Runtime.java:418)
at java.base/java.lang.Runtime.exec(Runtime.java:315)
at Base.TestBase.runReport(TestBase.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:344)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
at java.base/java.lang.ProcessImpl.create(Native Method)
at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:494)
at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:159)
at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
... 24 more
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- runReport -->
      </class> <!-- TestCases.LoginPageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
